version: '3.8'
services:
  bank-service:
    image: bank_service
    build:
      context: ./bank-service
      dockerfile: Dockerfile
    container_name: bank_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank-service-db
    ports:
      - "8185:8185"
    depends_on:
      - bank-service-db
    networks:
      - bank_service_network

  bank-service-db:
    image: postgres:14.7-alpine
    container_name: bank_service_db
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: bank-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - bank_service_network
    restart: on-failure

networks:
  bank_service_network:
    external: true
    name: bank_service_network